# Generated by Django 4.1.9 on 2023-06-25 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Viewer', 'Viewer')], default='Admin', max_length=20)),
                ('firstName', models.CharField(max_length=255)),
                ('middleName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('countryCode', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('lastLogin', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[('ADDTASK', 'Addtask'), ('DELETETASK', 'Deletetask'), ('UPDATETASK', 'Updatetask'), ('GETTASK', 'Gettask')], max_length=20)),
                ('hours', models.FloatField(default=0)),
                ('plannedStartDate', models.DateTimeField(blank=True, null=True)),
                ('plannedEndDate', models.DateTimeField(blank=True, null=True)),
                ('actualStartDate', models.DateTimeField(blank=True, null=True)),
                ('actualEndDate', models.DateTimeField(blank=True, null=True)),
                ('context', models.TextField()),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'unique_together': {('userId', 'taskId')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activity')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'unique_together': {('taskId', 'activityId')},
            },
        ),
    ]
